// src/containers/DeletedNotes/index.tsx
import React, { useState, useEffect } from 'react'

// Firebase
import { database, auth } from 'firebase/init'

// React redux connection
import { connect } from 'react-redux'

// Redux actions
import overviewActions from 'store/actions/overview'
import navActions from 'store/actions/navigation'
import deletedNotesActions from 'store/actions/deletedNotes'

// Components
import Button from 'components/UI/Button'
import Spinner from 'components/UI/Spinner'
import FeedbackModal from 'components/UI/FeedbackModal'

// Icons
import { Icon } from '@iconify/react'
import selectAllIcon from '@iconify/icons-mdi/select-all'
import selectOffIcon from '@iconify/icons-mdi/select-off'
import selectInverseIcon from '@iconify/icons-mdi/select-inverse'
import skullIcon from '@iconify/icons-mdi/skull'
import homeIcon from '@iconify/icons-mdi/home'
import vectorArrangeAboveIcon from '@iconify/icons-mdi/vector-arrange-above'
import fileRestoreIcon from '@iconify/icons-mdi/file-restore'
import magnifyIcon from '@iconify/icons-mdi/magnify'
import closeIcon from '@iconify/icons-mdi/close'
import successIcon from '@iconify/icons-mdi/checkbox-marked-circle-outline'
import errorIcon from '@iconify/icons-mdi/close-circle-outline'

// CSS styles
import './styles.css'

// Interfaces
import { Note, Option } from 'interfaces'

// Global functions
import {
    selectAll,
    unselectAll,
    sendNotesTo,
    sortFunction,
    invertSelection
} from 'globalfn'

interface Props {
    trash: Note[],
    multiselection: boolean,
    [key: string]: any
}

function DeletedNotes(props: Props) {
    const [allTrash, setAllTrash] = useState<Note[]>([])
    const [filteredTrash, setFilteredTrash] = useState<Note[]>([])
    const [filter, setFilter] = useState('all')
    const [order, setOrder] = useState('title')
    const [loading, setLoading] = useState(true)
    const [feedbackModal, setFeedbackModal] = useState<JSX.Element | null>(null)

    // Order by
    useEffect(() => {
        if (filteredTrash.length > 0) {
            const newfilteredTrash =
                filteredTrash.sort((a, b) => sortFunction(a, b, order))
            setFilteredTrash([...newfilteredTrash])
        }
    }, [order, filteredTrash.length]) // eslint-disable-line

    // Filter by color
    useEffect(() => {
        if (filter) {
            if (filter !== 'all')
                setFilteredTrash(allTrash.filter(note => note.color === filter))
            else setFilteredTrash([...allTrash])
        }
    }, [filter, allTrash])

    // Search notes
    useEffect(() => {
        if (props.search) {
            const searchRegExp = new RegExp(`^${props.search}[a-z0-9-_]?`, 'i')
            setFilteredTrash(
                allTrash.filter(
                    note => note.title.toLowerCase().match(searchRegExp)
                )
            )
        } else setFilteredTrash(allTrash)
    }, [props.search]) // eslint-disable-line

    const navOptions: Option[] = [
        {
            text: "Notes",
            icon: <Icon icon={homeIcon} />,
            type: "normal",
            click: () => props.history.push('/home/overview')
        },
        {
            text: "Order By",
            first: 'Title',
            type: "dropdown",
            items: ["Title", "Creation", "Modification", "Deletion"],
            onOptionSelect: (ord: string) => {
                const parsedOrder = ord.toLowerCase()
                setOrder(parsedOrder)
            }
        },
        {
            text: "Filter",
            first: 'All',
            type: "dropdown",
            items: [
                "All",
                "Orange",
                "Green",
                "Purple",
                "Grey",
                "Red",
                "Yellow",
                "Blue",
                "Black",
                "White"
            ],
            onOptionSelect: (filter: string) => setFilter(filter.toLowerCase())
        },
        {
            text: "Multiselection",
            icon: <Icon icon={vectorArrangeAboveIcon} />,
            type: "normal",
            click: props.toggleMultiselection
        }
    ]

    useEffect(() => {
        props.toggleMultiselection(false)
        auth.onAuthStateChanged(authState => {
            if (authState) {
                const user = auth.currentUser?.uid
                database.collection('users').doc(user).get()
                    .then(doc => {
                        props.setTrash(doc.data()!.trash)
                        setLoading(false)
                    })
            }
        })
        props.setOptions(navOptions)
    }, []) // eslint-disable-line

    useEffect(() => {
        setAllTrash(props.trash)
        setFilteredTrash([...props.trash.sort((a, b) => sortFunction(a, b, order))])
    }, [props.trash]) // eslint-disable-line

    function onNoteCardClick(noteId: string) {
        if (props.multiselection) {
            const newNotes = filteredTrash.map(note => {
                if (note.id !== noteId) return note
                else return { ...note, selected: !note.selected }
            })
            setFilteredTrash(newNotes)
        } else {
            props.seeDeletedNote(filteredTrash.filter(note => note.id === noteId)[0])
            props.history.push('/home/view-deleted-note')
        }
    }

    function destroySelectedProcess() {
        setLoading(true)
        const trash = filteredTrash.filter(note => !note.selected)
        database.collection('users').doc(auth.currentUser?.uid).update({ trash })
            .then(() => {
                setLoading(false)
                setFeedbackModal((
                    <FeedbackModal
                        feedback="All notes have been destroyed successfully."
                        icon={<Icon icon={successIcon} />}
                        hasAction
                        actionLabel={["Ok"]}
                        onModalAction={[() => {
                            props.toggleMultiselection(false)
                            props.setTrash(trash)
                            setFeedbackModal(null)
                        }]}
                    />
                ))
            }).catch(error => {
                setLoading(false)
                setFeedbackModal((
                    <FeedbackModal
                        feedback={`An error occurred while destroying the notes: ${error.message}`}
                        hasAction
                        icon={<Icon icon={errorIcon} />}
                        onModalAction={[() => setFeedbackModal(null)]}
                        actionLabel={["Ok"]}
                    />
                ))
            })
    }

    function destroySelected() {
        setFeedbackModal((
            <FeedbackModal
                feedback={`All notes selected will be destroyed. 
                This action cannot be undone. Continue?`}
                hasAction
                actionLabel={["Continue", "Cancel"]}
                onModalAction={[destroySelectedProcess, () => setFeedbackModal(null)]}
            />
        ))
    }

    function restoreSelectedProcess() {
        const delNotes = filteredTrash.filter(note => note.selected)
        setLoading(true)
        sendNotesTo("trash", "notes", delNotes)
            .then(res => {
                setLoading(false)
                setFeedbackModal((
                    <FeedbackModal
                        feedback="All notes selected have been restored successfully."
                        icon={<Icon icon={successIcon} />}
                        hasAction
                        actionLabel={["Ok"]}
                        onModalAction={[() => {
                            props.setNotes(res.notes)
                            props.setTrash(res.trash)
                            props.toggleMultiselection(false)
                            setFeedbackModal(null)
                        }]}
                    />
                ))
            }).catch(error => {
                setLoading(false)
                setFeedbackModal((
                    <FeedbackModal
                        feedback={`An error occurred while restoring the notes: ${error.message}`}
                        hasAction
                        icon={<Icon icon={errorIcon} />}
                        onModalAction={[() => setFeedbackModal(null)]}
                        actionLabel={["Ok"]}
                    />
                ))
            })
    }

    function restoreSelected() {
        setFeedbackModal((
            <FeedbackModal
                feedback="All notes selected will be restored. Continue?"
                hasAction
                actionLabel={["Continue", "Cancel"]}
                onModalAction={[restoreSelectedProcess, () => setFeedbackModal(null)]}
            />
        ))

    }

    const mainContent = (
        <>
            <div className={[
                "MultiselectionOptions",
                props.multiselection && filteredTrash.length > 0
                    ? "Show"
                    : ""
            ].join(' ')}>
                <Button
                    onclick={
                        () => setFilteredTrash(
                            selectAll(filteredTrash)
                        )}>
                    <Icon icon={selectAllIcon} />
                    <span>Select All</span>
                </Button>
                <Button
                    onclick={
                        () => setFilteredTrash(
                            unselectAll(filteredTrash)
                        )}>
                    <Icon icon={selectOffIcon} />
                    <span>Unselect All</span>
                </Button>
                <Button
                    onclick={() => setFilteredTrash(
                        invertSelection(filteredTrash)
                    )}>
                    <Icon icon={selectInverseIcon} />
                    <span>Invert Selection</span>
                </Button>
                <Button btnType="Danger" onclick={destroySelected}>
                    <Icon icon={skullIcon} />
                    <span>Destroy Selected</span>
                </Button>
                <Button btnType="Success" onclick={restoreSelected}>
                    <Icon icon={fileRestoreIcon} />
                    <span>Restore Selected</span>
                </Button>
            </div>

            <div className="NotesOverview">
                {filteredTrash.map(note => (
                    <div
                        key={note.id}
                        className="NoteCard"
                        onClick={() => onNoteCardClick(note.id)}
                    >
                        <div
                            className="NoteCardSelector"
                            style={{ backgroundColor: note.color }}
                        >
                            {
                                props.multiselection &&
                                <input
                                    type="checkbox"
                                    readOnly
                                    checked={note.selected}
                                />
                            }
                        </div>
                        <div className="NoteCardContent">
                            <span>{note.title}</span>
                            <p>
                                {
                                    note.content &&
                                    (
                                        note.content.length <= 40
                                            ? note.content
                                            : note.content
                                                .substring(0, 39)
                                                .concat('...')
                                    )
                                }
                            </p>
                        </div>
                    </div>
                ))}
            </div>
        </>
    )

    const trashEmptyFeedback = (
        <FeedbackModal
            hasAction={false}
            feedback={`Deleted notes will appear here.`}
        />
    )

    const filteredTrashEmptyFeedback = (
        <FeedbackModal
            hasAction={false}
            feedback={`No notes found. Try another filter / search.`}
            icon={(
                <div className="NoNotesFound">
                    <Icon icon={magnifyIcon} />
                    <Icon icon={closeIcon} />
                </div>
            )}
        />
    )

    return (
        <div className="DeletedNotes">
            {
                loading
                    ? <div className="SpinnerResizer"><Spinner /></div>
                    : allTrash.length === 0
                        ? trashEmptyFeedback
                        : filteredTrash.length === 0
                            ? filteredTrashEmptyFeedback
                            : feedbackModal !== null
                                ? feedbackModal
                                : mainContent
            }
        </div>
    )
}

function mapStateToProps(state: any) {
    return {
        trash: state.deletedNotes.trash,
        multiselection: state.navigation.multiselection,
        currentUser: state.navigation.currentUser,
        search: state.navigation.search
    }
}

function mapDispatchToProps(dispatch: any) {
    return {
        setOptions(options: any) { dispatch(navActions.setOptions(options)) },
        toggleMultiselection(mode?: boolean) { dispatch(navActions.toggleMultiselection(mode)) },
        setTrash(trash: any) { dispatch(deletedNotesActions.setTrash(trash)) },
        seeDeletedNote(note: Note) { dispatch(navActions.setCurrentNote(note)) },
        setNotes(notes: Note[]) { dispatch(overviewActions.setNotes(notes)) },
        setCurrentNote(note: Note) { dispatch(navActions.setCurrentNote(note)) }
    }
}

export default connect(mapStateToProps, mapDispatchToProps)(DeletedNotes)

// src/components/home/pages/DeletedNotes.vue
<template>
  <div class="deleted-notes">
    <div v-if="trashSelected.length >= 1">
      <div class="buttons">
        <div class="d-inline-flex">
          <v-btn @click="selectAll" class="multiselection-option">
            <v-icon left>mdi-select-all</v-icon>
            Select all
          </v-btn>
          <v-btn @click="unselectAll" class="multiselection-option">
            <v-icon left>mdi-select-off</v-icon>
            Unselect all
          </v-btn>
          <v-btn @click="invertAll" class="multiselection-option">
            <v-icon left>mdi-select-inverse</v-icon>
            Invert selection
          </v-btn>
          <v-btn @click="deleteSelected" class="red lighten-1 white--text multiselection-option">
            <v-icon left>mdi-delete-circle-outline</v-icon>
            Delete
          </v-btn>
          <v-btn @click="restoreSelected" class="green lighten-1 white--text multiselection-option">
            <v-icon left>mdi-file-restore-outline</v-icon>
            Restore
          </v-btn>
        </div>
      </div>
    </div>

    <v-container class="d-inline-flex">
      <!-- Loading circle -->
      <div v-if="!loaded">
        <v-progress-circular
          class="loading"
          indeterminate
          rotate
          size="120"
          color="grey darken-2"
        ></v-progress-circular>
      </div>

      <v-row v-else>
          <div v-if="trash.length === 0" class="trash-info">
              <v-img
                src="@/assets/empty-trash-icon.png"
                width="200"
                height="200"
              ></v-img>
              <span class="display-2">Trash empty</span>
          </div>

          <div v-else-if="filteredTrash.length === 0" class="trash-info">
              <v-img
                src="@/assets/not-found-icon.png"
                width="200"
                height="200"
              ></v-img>
              <span class="display-2">No notes found. Try a different filter</span>
          </div>

        <!-- Note cards -->
        <v-col v-else cols="12" sm="4" md="3" v-for="note in filteredTrash" :key="note.id">
          <v-hover v-slot:default="{ hover }">
            <v-card 
              @click="clickHandler(note)" 
              :elevation="hover?'8':'2'" 
              class="grey lighten-3 note"
            >
              <v-checkbox
                v-if="multiselect"
                :value="hovering"
                v-model="note.selected"
                @click="note.selected = !note.selected"
                :color="note.color.toLowerCase()"
                hide-details
                class="check-note"
              ></v-checkbox>

              <div class="filter-bar" :style="{background: note.color}"></div>
              <v-card-title>{{note.title | minifyTitle}}</v-card-title>
              <v-card-text>{{note.body | minifyContent}}</v-card-text>
            </v-card>
          </v-hover>
        </v-col>

      </v-row>
    </v-container>
  </div>
</template>

<script>
import { mapGetters, mapActions } from "vuex";
export default {
  name: "DeletedNotes",
  data() {
    return {
      multiselect: false,
      hovering: false,
      trashSelected: new Array(),
      options: [
        { 
          text: "Home", 
          icon: "mdi-home", 
          type: "normal", 
          click: ()=>{this.gotoOverview()} 
        },
        {
          text: "Order By",
          slug: "order-by",
          first: 'Title',
          icon: "mdi-order-alphabetical-ascending",
          type: "dropdown",
          options: ["Title", "Creation", "Modification", "Deletion"],
          click: function(){}
        },
        {
          text: "Filter",
          slug: "filter",
          first: 'All',
          icon: "mdi-flag",
          type: "dropdown",
          options: [
            "All",
            "Orange",
            "Green",
            "Purple",
            "Grey",
            "Red",
            "Yellow",
            "Blue",
            "Black",
            "White"
          ],
          click: function(){}
        },
        { text: "Multiselection",
          icon: "mdi-vector-arrange-above",
          type: "normal",
          click: ()=>{this.multiselection()}
        }
      ]
    };
  },
  computed: {
    ...mapGetters(["loaded", "search", "order", "filter", "currentNote", "trash"]),
    filteredTrash() {
      return this.trash.filter(note => {
        if (note.title.toLowerCase().match(this.search.toLowerCase())) {
          if (this.filter === "All") return note;
          else if (note.color === this.filter) return note;
        }
      }).sort((a, b)=>{
        if(a[this.order] > b[this.order]) return 1
        else if(a[this.order] < b[this.order]) return -1
        else return 0
      })
    }
  },
  methods: {
    ...mapActions([
      "setTrash", 
      "setView", 
      "setCurrentNote", 
      "setOrder", 
      "setFilter",
      "deletePermanently",
      "restoreNotes"
    ]),
    clickHandler(note) {
      if(!this.multiselect) {
        this.setCurrentNote(note)
        this.$emit('changeView', 'ViewDeletedNote')
      }
      else {
        note.selected = !note.selected
        if(note.selected) {
          this.trashSelected.push(note)
        } else {
          this.trashSelected = this.trashSelected.filter(n=>n.id!==note.id)
        }
      } 
    },
    multiselection() {
      this.multiselect = !this.multiselect
      if(!this.multiselect) {
        const resetNotesSelectedState = this.trash.filter(note=>{
          if(note.selected)
            note.selected = false
          return note
        })
        this.$store.commit('setTrash', resetNotesSelectedState)
        this.setTrash(resetNotesSelectedState)
        this.trashSelected = new Array()
      }
    },
    selectAll() {
      this.trash.forEach(note=>note.selected = true)
      this.trashSelected = this.trash
    },
    unselectAll() {
      this.trash.forEach(note=>note.selected = false)
      this.trashSelected = new Array()
    },
    invertAll() {
      this.trashSelected = new Array()
      this.trash.forEach(note=>{
        note.selected = note.selected ? false : true
        if(note.selected) this.trashSelected.push(note)
      })
    },
    deleteSelected() {
      const response = confirm('All notes selected will be deleted PERMANENTLY.')
      if(response) {
        this.deletePermanently(this.trashSelected)
          .then(()=>{
            this.multiselect = false
            this.trashSelected = new Array()
          })
          .catch(err=>alert(`Error while deleting notes: ${err.message}`))
      }
    },
    restoreSelected() {
      const response = confirm('All notes selected will be restored.')
      if(response) {
        this.restoreNotes(this.trashSelected)
          .then(()=>{
            this.multiselect = false
            this.trashSelected = new Array()
          })
          .catch(err=>alert(`Error while restoring notes: ${err.message}`))
      }
    },
    capitalize(string) {
      let result = string.split('')
      result[0] = result[0].toLocaleUpperCase()
      return result.join('')
    },
    gotoOverview() {
      this.setOrder('title')
      this.setFilter('All')
      this.$emit('changeView', 'Overview')
    }
  },
  created() {
    this.$emit("changeOptions", this.options)
    this.setView('DeletedNotes')
    this.setTrash()
    this.options[1].first = this.capitalize(this.order)
    this.options[2].first = this.filter
  },
  filters: {
    minifyTitle(value) {
      if (value.length > 30) return value.slice(0, 29) + "...";
      return value;
    },
    minifyContent(value) {
      if (value.length > 100) return value.slice(0, 99) + "...";
      return value;
    }
  }
};
</script>

<style>
.deleted-notes .trash-info {
  width: 100%;
  height: fit-content;
  transform: translateY(50%);
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  user-select: none;
}
.deleted-notes .buttons {
  width: fit-content;
  margin: 0 auto;
}
.deleted-notes .multiselection-option {
  margin-right: 10px;
}
.deleted-notes .loading {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
.deleted-notes .note {
  cursor: pointer;
  user-select: none;
  width: 250px;
  height: 250px;
  padding: 10px;
  overflow: auto;
}
.deleted-notes .add-sign {
  display: flex;
  align-items: center;
  justify-content: center;
}
.deleted-notes .filter-bar {
  width: 100%;
  height: 5px;
}
.deleted-notes .check-note {
  margin: 0 0 0 90%;
  width: fit-content;
  height: fit-content;
  padding: 0;
}
</style>
